### ISSUE TITLE
O projeto

### ISSUE THREAD

**Issue by alissonandrade2020** [GabriellArthur/DashGo-ReactJs#2]
Boa tarde Gabriel!

o projeto tá completo ?? 

baixei o projeto e fiz o que pede na descrição mas ele não funciona

**Comment by GabriellArthur** [comment]
Boa tarde Alisson

Está completo sim, acabei de fazer algumas alterações porquê eu tinha juntado todos os comandos no "yarn dev" mas agora está documentado certinho.
