### ISSUE TITLE
Nada

### ISSUE THREAD

**Issue by alissonandrade2020** [GabriellArthur/DashGo-ReactJs#3]
ainda não fncionou

**Comment by GabriellArthur** [comment]
Então faz assim:
1°Deleta o projeto
2°Clona novamente o projeto
3°Certifica que o yarn está instalado
  3.1 - Certifica que o .env está na pasta, caso não esteja, escreva "JWT_SECRET=secret"
4°Rode o comando "yarn" no terminal para baixar todas as dependencias
5°Rode o comando "yarn prisma db push" para gerar o Prisma Client
6°Rode o comando "yarn dev" para iniciar
7°Entre no navegador no endereço "http://localhost:3000/"
8°Faça o login(administrador@dashgo.net) e senha(admin)

Se aparecer algum error, me envie.

**Comment by alissonandrade2020** [comment]
![image](https://user-images.githubusercontent.com/39311340/167862493-7dc03320-791c-483f-a4aa-dc1e07d9d6be.png)

**Comment by alissonandrade2020** [comment]
consegui !
